# SPDX-FileCopyrightText: 2025 Yansheng Wang <ywang889@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

site_name: "S-parameter Post-Processing and Reporting"

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - Tutorials: tutorials.md
  - How-to Guides: how_to_guides.md
  - Reference: reference.md
  - Explanation: explanation.md
