# SPDX-FileCopyrightText: 2025 Yansheng Wang <ywang889@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "spara_reporting"
SPDX-PackageSupplier = "Yansheng Wang <ywang889@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/Bellwether88/spara_reporting"

[[annotations]]
path = "data/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Yansheng Wang <ywang889@gmail.com>"
SPDX-License-Identifier = "Apache-2.0"
